config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'prices', to: 'prices#prices'
  post 'update_key', to: 'home#update_key'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  include ShopifyApp::SessionStorage

  def self.customer_key
  end
  

end

app/models/shopify_hook.rb
class ShopifyHook < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthenticatedController
  skip_before_action :verify_authenticity_token
  before_action :set_shop
  
  def index; end
  
  def update_key  
    redirect_params = test_and_save_api_key

    if @shop.carrier_created?
      create_carrier_service

      @shop.update! carrier_created: true
    end
    
    redirect_to root_path(redirect_params)
  end

  private
  def create_carrier_service
    body = JSON.load(Rails.root.join('carrier_service.json'))
    body['carrier_service']['callback_url'] = "#{request.base_url}/prices"

    headers = {content_type: :json, accept: :json}
    headers["X-Shopify-Access-Token"] = "#{shop.shopify_token}"
    
    url = "https://#{shop.shopify_domain}/admin/carrier_services"
    RestClient.post(url, body.to_json, headers)
  end

  def test_and_save_api_key
    begin
      RestClient.get("https://flashcalculador.com.br/api/v2/calcular_frete?cliente_chave=#{params[:api_key]}&cep_destino=00000000&peso_gramas=1000")
      @shop.update customer_key: params[:api_key], active: params[:active].present?
      return {}
    rescue
      return {message: "Chave de API inválida"} 
    end
  end

  def set_shop
    @shop = Shop.find_by_shopify_domain(current_shopify_domain)
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def prices    
    ShopifyHook.create log_string: {params: params.permit!.to_h}

      @nome_loja = params[:rate][:origin][:company_name]+".myshopify.com".downcase
      @nome_loja = @nome_loja.downcase

      key = Shop.where(shopify_domain:"#{@nome_loja}").pluck(:customer_key)

      
      @cliente_chave = key.reduce  
      # cliente_chave = "\"#{@cliente_chave}\"".gsub("\"", "")
      @cep_destino = params[:rate][:destination][:postal_code] rescue nil
      @peso_gramas =  params[:rate][:items].map{|item| (item[:grams] * item[:quantity])}.sum

      
      #binding.pry
      
      url = URI.escape("https://flashcalculador.com.br/api/v2/calcular_frete?cliente_chave=#{@cliente_chave}&cep_destino=#{@cep_destino}&peso_gramas=#{@peso_gramas}")
      
      #binding.pry
      
      hash = RestClient.get(url) 
      shopify_rates = eval(hash)
      
      #binding.pry
      
      rates_products = []
      shopify_rates[:products].each do |p|
        p.each do |key, value|
          product_rate = p.values
          rates_products << {
            service_name: key,
            service_code: 123,#key.parameterize,# (se não funcionar pode deixar 123 pra teste e depois vemos o que fazer)
            total_price: product_rate.reduce[:preco].to_s.delete('.'), # == R$10,00
            currency: 'BRL',
            min_delivery_date: Date.today + product_rate.reduce[:prazo_min].to_i.days,
            max_delivery_date: Date.today + product_rate.reduce[:prazo_max].to_i.days
          }
        end
      end  

      rates = Hash.new 
      rates[:rates] = rates_products    
      render json: rates
       
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>
<div id="demo" class="PolarisDemo" style="padding: 20px">
    <div class="TZK5E">
        <div>
            <div style="--top-bar-background: #00848e; --top-bar-background-lighter: #1d9ba4; --top-bar-color: #f9fafb; --p-frame-offset: 0px;">
                <form method="post" action="<%= update_key_url %>">
                    <div class="Polaris-FormLayout">
                        <div class="Polaris-FormLayout__Item">
                            <% if params[:message].present? %>
                                <div style="--top-bar-background:#00848e; --top-bar-background-lighter:#1d9ba4; --top-bar-color:#f9fafb; --p-frame-offset:0px;">
                                    <div class="Polaris-Banner Polaris-Banner--statusCritical Polaris-Banner--withinPage" tabindex="0" role="alert" aria-live="polite" aria-labelledby="Banner6Heading" aria-describedby="Banner6Content">
                                        <div class="Polaris-Banner__Ribbon">
                                            <span class="Polaris-Icon Polaris-Icon--colorRedDark Polaris-Icon--isColored Polaris-Icon--hasBackdrop">
                                                <svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
                                                <circle fill="currentColor" cx="10" cy="10" r="9"></circle>
                                                <path d="M2 10c0-1.846.635-3.543 1.688-4.897l11.209 11.209A7.954 7.954 0 0 1 10 18c-4.411 0-8-3.589-8-8m14.312 4.897L5.103 3.688A7.954 7.954 0 0 1 10 2c4.411 0 8 3.589 8 8a7.952 7.952 0 0 1-1.688 4.897M0 10c0 5.514 4.486 10 10 10s10-4.486 10-10S15.514 0 10 0 0 4.486 0 10"></path>
                                                </svg>
                                            </span>
                                        </div>
                                        <div class="Polaris-Banner__ContentWrapper">
                                            <div class="Polaris-Banner__Heading" id="Banner6Heading">
                                                <p class="Polaris-Heading"><%= params[:message] %></p>
                                            </div>
                                            <div class="Polaris-Banner__Content" id="Banner6Content">
                                                <p>Solicite uma nova chave a equipe Flash Courier DDX.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                            
                            <br>
                            <label class="Polaris-Choice" for="PolarisCheckbox2">
                                <span class="Polaris-Choice__Control">
                                    <span class="Polaris-Checkbox">
                                        <input id="PolarisCheckbox2" name="active" type="checkbox" class="Polaris-Checkbox__Input" aria-invalid="false" role="checkbox" aria-checked="false" value="true" <%= 'checked="true"' if @shop.active? %> /><span class="Polaris-Checkbox__Backdrop"></span>
                                        <span class="Polaris-Checkbox__Icon">
                                            <span class="Polaris-Icon">
                                                <svg viewBox="0 0 20 20" class="Polaris-Icon__Svg" focusable="false" aria-hidden="true">
                                                    <path
                                                        d="M8.315 13.859l-3.182-3.417a.506.506 0 0 1 0-.684l.643-.683a.437.437 0 0 1 .642 0l2.22 2.393 4.942-5.327a.437.437 0 0 1 .643 0l.643.684a.504.504 0 0 1 0 .683l-5.91 6.35a.437.437 0 0 1-.642 0"
                                                    ></path>
                                                </svg>
                                            </span>
                                        </span>
                                    </span>
                                </span>
                                <span class="Polaris-Choice__Label">Ativar Flash Courier?</span>
                            </label>
                        </div>
                        <div class="Polaris-FormLayout__Item">
                            <div class="">
                                <div class="Polaris-Labelled__LabelWrapper">
                                    <div class="Polaris-Label"><label id="PolarisTextField2Label" for="PolarisTextField2" class="Polaris-Label__Text">Chave de API Flash Courier DDX</label></div>
                                </div>
                                <div class="Polaris-Connected">
                                    <div class="Polaris-Connected__Item Polaris-Connected__Item--primary">
                                        <div class="Polaris-TextField">
                                            <input
                                                id="PolarisTextField2"
                                                class="Polaris-TextField__Input"
                                                type="text"
                                                aria-describedby="PolarisTextField2HelpText"
                                                aria-labelledby="PolarisTextField2Label"
                                                aria-invalid="false"
                                                aria-multiline="false"
                                                name="api_key"
                                                value="<%= @shop.customer_key %>"
                                            />
                                            <div class="Polaris-TextField__Backdrop"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="Polaris-Labelled__HelpText" id="PolarisTextField2HelpText"><span>Chave fornecida pela equipe Flash Courier DDX.</span></div>
                            </div>
                        </div>
                        <div class="Polaris-FormLayout__Item">
                            <button type="submit" class="Polaris-Button">
                                <span class="Polaris-Button__Content"><span class="Polaris-Button__Text">Salvar</span></span>
                            </button>
                        </div>
                    </div>
                    <span class="Polaris-VisuallyHidden"><button type="submit" aria-hidden="true" tabindex="-1">Salvar</button></span>
                </form>
            </div>
        </div>
        <div></div>
    </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'turbolinks:load' : 'DOMContentLoaded';

  if (!document.documentElement.hasAttribute("data-turbolinks-preview")) {
    document.addEventListener(eventName, function flash() {
      <% if flash[:notice] %>
        ShopifyApp.flashNotice(<%== flash[:notice].to_json %>);
      <% end %>

      <% if flash[:error] %>
        ShopifyApp.flashError(<%== flash[:error].to_json %>);
      <% end %>
                             
      document.removeEventListener(eventName, flash)
    });
  }
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashShopify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
     <link
  rel="stylesheet"
  href="https://unpkg.com/@shopify/polaris@4.0.0/styles.min.css"
/>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>